# Generated by Django 5.1.1 on 2025-04-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bookings_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='address',
        ),
    ]
