# Generated by Django 5.1.1 on 2025-04-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_details_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='address',
            field=models.TextField(default='Unknown', max_length=255),
        ),
    ]
