# Generated by Django 5.1.1 on 2025-04-09 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_details_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.decoration'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.food'),
        ),
    ]
